#!/usr/bin/env node
/**
 * Post-build script to ensure pretty URLs work for blog posts.
 * It scans the `out/blog` directory for top-level `.html` files
 * and creates a sibling folder for each slug with an `index.html` copy.
 */

const fs = require('fs');
const path = require('path');

const OUT_DIR = path.join(__dirname, '..', 'out');
const BLOG_DIR = path.join(OUT_DIR, 'blog');

console.log('📝 Post-build: Creating blog index.html files...');

if (!fs.existsSync(BLOG_DIR)) {
  console.warn('⚠️  Blog output directory not found:', BLOG_DIR);
  process.exit(0);
}

const entries = fs.readdirSync(BLOG_DIR);
let successCount = 0;
let skippedCount = 0;
let errorCount = 0;

entries.forEach((entry) => {
  // Only process top-level .html files (exclude autogenerated __next files)
  if (!entry.endsWith('.html')) return;
  if (entry.startsWith('__next')) return;
  if (entry === 'blog.html') return; // leave blog.html alone

  const slug = path.basename(entry, '.html');
  const sourceFile = path.join(BLOG_DIR, entry);
  const targetDir = path.join(BLOG_DIR, slug);
  const targetFile = path.join(targetDir, 'index.html');

  try {
    if (!fs.existsSync(sourceFile)) {
      console.warn(`⚠️  Source file not found: ${sourceFile}`);
      skippedCount++;
      return;
    }

    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
    }

    fs.copyFileSync(sourceFile, targetFile);
    console.log(`✓ Created ${path.join('blog', slug, 'index.html')}`);
    successCount++;
  } catch (err) {
    console.error(`✗ Failed to create ${slug}/index.html:`, err.message);
    errorCount++;
  }
});

console.log(
  `\n✅ Post-build complete: ${successCount} files created${skippedCount ? `, ${skippedCount} skipped` : ''}${errorCount ? `, ${errorCount} errors` : ''}`
);

if (errorCount > 0) process.exit(1);
